### ISSUE TITLE
Roadmap for v1.0.0

### ISSUE THREAD

**Issue by randomdevpete** [randomdevpete/jarl#1]
- [x] Refactor all HOCs into a single one
- [x] Implement Router function-as-child component
- [x] Finish major breaking rename of everything
- [x] React Native package
- [x] Get guides, API docs and demos to passable quality
- [x] and publish them
- [x] Maybe some docs or deprecation info around Redux integration
- [x] Fixed flaky timed tests with different approach
- [x] Merge into master branch
- [x] CI pipeline
- [x] Get builds, publishing, demos site deployment fully automated
- [x] Beta release
- [ ] Server Side Rendering API and guide
- [ ] Properly test RN and make a demo, poss. E2E
- [x] Figure out why isActive doesn't work inside demos
- [ ] Further polish and finalisation of docs for v1

**Comment by randomdevpete** [comment]
Superceded entirely by v2
